import { Component, Input, OnInit } from '@angular/core';
import { ModalController } from '@ionic/angular';
import { DefaultValuesInterface } from '@interfaces/game.interface';


@Component({
  selector: 'app-training-modal',
  templateUrl: './training-modal.component.html',
  styleUrls: ['./training-modal.component.scss'],
})
export class TrainingModalComponent implements OnInit {

  public openingOptions = [
    'Alekhine Defense',
    'Amar Gambit',
    'Amar Opening',
    'Amazon Attack',
    'Amsterdam Attack',
    'Anderssen Opening',
    'Australian Defense',
    'Barnes Defense',
    'Barnes Opening',
    'Benko Gambit',
    'Benko Gambit Accepted',
    'Benko Gambit Declined',
    'Benoni Defense',
    'Bird Opening',
    'Bishop\'s Opening',
    'Blackburne Shilling Gambit',
    'Blackmar-Diemer Gambit',
    'Blackmar-Diemer Gambit Declined',
    'Blackmar-Diemer, Lemberger Countergambit',
    'Blumenfeld Countergambit',
    'Blumenfeld Countergambit Accepted',
    'Boden-Kieseritzky Gambit',
    'Bogo-Indian Defense',
    'Bongcloud Attack',
    'Borg Defense',
    'Borg Opening',
    'Bronstein Gambit',
    'Budapest Defense',
    'Canard Opening',
    'Caro-Kann Defense',
    'Carr Defense',
    'Catalan Opening',
    'Center Game',
    'Center Game Accepted',
    'Clemenz Opening',
    'Colle System',
    'Colle System, 3. e3 e6 4. Bd3',
    'Crab Opening',
    'Creepy Crawly Formation',
    'Czech Defense',
    'Danish Gambit',
    'Danish Gambit Accepted',
    'Danish Gambit Declined, Sorensen Defense',
    'Doery Defense',
    'Dresden Opening',
    'Duras Gambit',
    'Dutch Defense',
    'Dutch Defense, 2. c4',
    'East Indian Defense',
    'Elephant Gambit',
    'English Defense',
    'English Opening',
    'English Openings',
    'English Orangutan',
    'English Rat',
    'Englund Gambit',
    'Englund Gambit Complex Declined',
    'Englund Gambit Complex',
    'Englund Gambit Declined',
    'Formation',
    'Four Knights Game',
    'Four Knights',
    'Franco-Benoni Defense',
    'French Defense',
    'Fried Fox Defense',
    'Gedult\'s Opening',
    'Giuoco Piano',
    'Global Opening',
    'Goldsmith Defense',
    'Grob Opening',
    'Gruenfeld Defense',
    'Guatemala Defense',
    'Gunderam Defense',
    'Hippopotamus Defense',
    'Horwitz Defense',
    'Hungarian Opening',
    'Indian Game',
    'Irish Gambit',
    'Italian Game',
    'Kadas Opening',
    'Kangaroo Defense',
    'King\'s Gambit',
    'King\'s Gambit',
    'King\'s Gambit',
    'King\'s Indian Attack',
    'King\'s Indian Defense',
    'King\'s Indian',
    'King\'s Knight Opening',
    'King\'s Pawn',
    'King\'s Pawn Game',
    'King\'s Pawn Opening',
    'Lasker Simul Special',
    'Latvian Gambit',
    'Latvian Gambit Accepted',
    'Lemming Defense',
    'Lion Defense',
    'London System',
    'Marienbad System',
    'Mexican Defense',
    'Mieses Opening',
    'Mikenas Defense',
    'Modern Defense',
    'Montevideo Defense',
    'Neo-Gruenfeld Defense',
    'Nimzo-Indian Defense',
    'Nimzo-Larsen Attack',
    'Nimzowitsch Defense',
    'Nimzowitsch Defense, Declined Variation',
    'Nimzowitsch-Larsen Attack',
    'Norwegian Defense',
    'Old Benoni Defense',
    'Old Indian Defense',
    'Old Indian Defense, 2. c4 d6',
    'Old Indian',
    'Owen Defense',
    'Paleface Attack',
    'Petrov\'s Defense',
    'Petrov',
    'Philidor Defense',
    'Pirc Defense',
    'Polish Defense',
    'Polish Opening',
    'Ponziani Opening',
    'Portuguese Opening',
    'Pterodactyl Defense',
    'Queen\'s Gambit',
    'Queen\'s Gambit Accepted',
    'Queen\'s Gambit Declined',
    'Queen\'s Gambit Refused',
    'Queen\'s Indian',
    'Queen\'s Pawn',
    'Rat Defense',
    'Reti Opening',
    'Richter-Veresov Attack',
    'Robatsch (Modern) Defense',
    'Robatsch Defense',
    'Rubinstein Opening',
    'Russian Game',
    'Ruy Lopez',
    'Ruy Lopez Defense, Halloween Attack',
    'Saragossa Opening',
    'Scandinavian Defense',
    'Scotch Gambit',
    'Scotch Game',
    'Scotch',
    'Semi-Bononi',
    'Semi-Slav Defense',
    'Semi-Slav Defense Accepted',
    'Sicilian Defense',
    'Slav Defense',
    'Slav Indian',
    'Sodium Attack',
    'Spanish Opening',
    'St. George Defense',
    'System',
    'Tarrasch Defense',
    'Tayler Opening',
    'Three Knights Opening',
    'Torre Attack',
    'Trompowsky Attack',
    'Valencia Opening',
    'Van Geet Opening',
    'Van\'t Kruijs Opening',
    'Venezolana Opening',
    'Veresov Opening',
    'Vienna Game',
    'Vulture Defense',
    'Wade Defense',
    'Ware Defense',
    'Ware Opening',
    'Yusupov-Rubinstein System',
    'Zaire Defense',
    'Zukertort Defense',
    'Zukertort Opening'
  ];
  // public opening = `Bishop's Opening`;
  public opening = `Queen's Gambit`;
  public userColor = `w`;
  @Input() defaultOpeningValues: DefaultValuesInterface;

  constructor(public modalController: ModalController) {
  }

  ngOnInit() {
    if (this.defaultOpeningValues) {
      this.opening = this.defaultOpeningValues.opening;
      this.userColor = this.defaultOpeningValues.userColor;
    }
  }

  public closeModal() {
    this.modalController.dismiss({
      opening: this.opening,
      userColor: this.userColor
    });
  }
}
